image:
  file: .gitpod.Dockerfile

tasks:
  - init: cd packages/shared && npm install && exit
  - init: cd packages/analytics-front && npm install && exit
  - init: cd packages/server && npm install && exit
  - init: cd packages/client && npm install && exit
  - init: cd packages/services && npm install && exit
  - init: npm install
