image:
  file: .gitpod.Dockerfile

tasks:
  - init: cd packages/shared && npm install && exit
  - init: cd packages/analytics-front && npm install && exit
  - init: cd packages/server && npm install && exit
  - init: cd packages/client && npm install && exit
  - init: cd packages/services && npm install && exit
  - init: npm install && chmod -R 777 .husky/

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.8:02aHhbJ0Q4aGdjHXlTdVKg==
    - bradlc.vscode-tailwindcss@0.5.9:yRBWziGXnf16R7jUzlgn5w==
    - stylelint.vscode-stylelint@0.86.0:b7wCsBPLKjtb6EgCXLO5sg==
    - formulahendry.auto-close-tag@0.5.10:GSIjAJo5b8OeW5FdWSDA8A==
    - steoates.autoimport@1.5.3:Tr3qYUEEq73wrKwCWaYivQ==
    - coenraads.bracket-pair-colorizer-2@0.1.4:+JUeb/jFYZt2/0MS/gUllA==
    - streetsidesoftware.code-spell-checker@1.10.2:IKNWSiKNhoiWZ0g+IVw/mA==
    - oouo-diogo-perdigao.docthis@0.8.2:lMa2IQ3494Vo08MVyma07w==
    - vincaslt.highlight-matching-tag@0.10.0:pP+bZ1YdLRE3UArege6hTw==
    - formulahendry.auto-rename-tag@0.1.6:giooMs6Faom2FfOHlydXmw==
    - anseki.vscode-color@0.4.5:6L3EhKJFHuizA7wqZz6/+g==
    - wix.vscode-import-cost@2.15.0:gY9pNjIYeM3FJyLNr4Bicw==
    - christian-kohler.npm-intellisense@1.2.2:OXx6idzXSYM8yU/TAjgFOw==
    - varharrie.import-beautify@0.3.0:u4dEBpxSldHIEr0p06vt7Q==
    - christian-kohler.path-intellisense@2.3.0:4aNBD+QUimscVO5NwoATiw==
    - pkief.material-icon-theme@4.5.0:ckDTVCTpdr4G0ZmIlQWkZA==